/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get service metadata
         * @description Retrieve top-level service health and identity information.
         */
        get: operations["getServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Probe endpoint for container orchestrators and load balancers to assess application liveness.
         */
        get: operations["getHealthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List refund requests
         * @description Retrieve a list of refund requests from the evaluation queue with optional
         *     status filtering. Records are ordered by creation timestamp descending.
         */
        get: operations["listRefundRequests"];
        put?: never;
        /**
         * Submit refund request for evaluation
         * @description Accept an incoming customer refund request, persist a pending record in DynamoDB,
         *     and schedule asynchronous multi-agent evaluation via LangGraph and AWS Bedrock.
         *     Supports JSON payload or multipart form data with an optional initial evidence photo.
         */
        post: operations["submitRefundRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds/{refundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get refund request details
         * @description Retrieve the latest status, agent classification, policy check outcome, evidence attachments,
         *     and final decision for a specific refund request.
         */
        get: operations["getRefundRequestById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds/{refundId}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually override refund decision
         * @description Apply a human operator decision override to an existing refund request (typically
         *     one escalated for human review). Transitions status to `completed` and records an
         *     audit trail of operator decision and rationale.
         */
        post: operations["overrideRefundDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds/{refundId}/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit customer clarification
         * @description Provide customer clarification response for a refund request that is paused in
         *     `awaiting_clarification` status. Supports plain JSON text responses or multipart form
         *     data with an optional attached evidence image. Automatically resumes multi-agent evaluation
         *     in the background.
         */
        post: operations["submitRefundClarification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds/{refundId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload photo evidence for a refund request
         * @description Upload a customer proof image (JPEG, PNG, WebP up to 5MB) for a refund request.
         *     If the refund request is currently paused in `awaiting_clarification` status, uploading
         *     evidence automatically enqueues background workflow resumption without requiring a separate
         *     call to `/clarify`.
         */
        post: operations["uploadRefundEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds/{refundId}/request-proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit reviewer proof request for an escalated refund
         * @description Accept an inquiry prompt from a human supervisor for an escalated refund request,
         *     generate a formal customer notification email instructing supported upload formats,
         *     and transition the refund record from `escalated` back to `awaiting_clarification`.
         */
        post: operations["requestReviewerProof"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ServiceInfo: {
            /**
             * @description Service health indicator.
             * @example ok
             */
            status: string;
            /**
             * @description Microservice identifier name.
             * @example refund-request-processor
             */
            service: string;
        };
        HealthStatus: {
            /**
             * @description Liveness status of the API service.
             * @example healthy
             */
            status: string;
        };
        /**
         * @description Lifecycle evaluation status of the refund request:
         *     * `pending`: In queue or actively being evaluated by multi-agent workflow.
         *     * `completed`: Decision reached (automated or manually overridden).
         *     * `escalated`: Escalated to human operator review due to low confidence, policy ambiguity, or order amount threshold.
         *     * `awaiting_clarification`: Paused awaiting customer details or photo clarification.
         * @example pending
         * @enum {string}
         */
        RefundStatus: "pending" | "completed" | "escalated" | "awaiting_clarification";
        /**
         * @description Outcome decision for the refund request:
         *     * `auto_approve`: Automatically approved by policy evaluation.
         *     * `deny`: Ineligible under policy rules.
         *     * `escalate`: Transferred to human review queue.
         *     * `approve`: Manually approved by human operator override.
         * @example auto_approve
         * @enum {string}
         */
        RefundDecision: "auto_approve" | "deny" | "escalate" | "approve";
        /**
         * @description Classified reason category determining policy rules and evidence mandates.
         * @example damaged
         * @enum {string}
         */
        RefundCategory: "damaged" | "wrong_item" | "changed_mind" | "late_delivery" | "missing_item";
        /**
         * @description Final determination selected by human reviewer.
         * @example approve
         * @enum {string}
         */
        OverrideDecisionType: "approve" | "deny";
        RefundCreateRequest: {
            /**
             * @description Associated purchase order identifier.
             * @example ORD-1001
             */
            orderId: string;
            /**
             * @description Customer-submitted explanation or reason for requesting a refund.
             * @example The ceramic vase arrived shattered inside the package with no protective bubble wrap.
             */
            customerRequestText: string;
        };
        RefundCreateResponse: {
            /**
             * @description Unique generated refund request identifier.
             * @example ref_7f9b1c2e3a4d
             */
            refundId: string;
            /**
             * @description Associated purchase order identifier.
             * @example ORD-1001
             */
            orderId: string;
            status: components["schemas"]["RefundStatus"];
            /**
             * Format: date-time
             * @description ISO-8601 creation timestamp.
             * @example 2026-09-23T14:15:30Z
             */
            createdAt: string;
        };
        RefundClarificationRequest: {
            /**
             * @description Customer-provided clarification response text.
             * @example The package was left at the front porch in heavy rain, soaked through.
             */
            responseText: string;
        };
        RefundOverrideRequest: {
            overrideDecision: components["schemas"]["OverrideDecisionType"];
            /**
             * @description Operator explanation justifying the manual decision override.
             * @example Photographic proof confirmed package damage prior to delivery.
             */
            overrideReason: string;
        };
        ReviewerProofRequest: {
            /**
             * @description Targeted proof request prompt sent to the customer.
             * @example Please provide a clear photo of the serial number sticker on the base of the device.
             */
            proofPrompt: string;
            /**
             * @description Optional customer name for email greeting.
             * @example Alex Morgan
             */
            customerName?: string | null;
        };
        EvidenceItem: {
            /**
             * @description Unique identifier for the uploaded evidence item.
             * @example evi_a1b2c3d4
             */
            evidenceId: string;
            /**
             * @description S3 or local filesystem storage key path.
             * @example refunds/ref_543c86069f0f/box_label.jpg
             */
            storageKey: string;
            /**
             * @description Original filename of the uploaded asset.
             * @example box_label.jpg
             */
            filename: string;
            /**
             * @description MIME content type of the image.
             * @example image/jpeg
             */
            contentType: string;
            /**
             * @description File size in bytes.
             * @example 154230
             */
            sizeBytes: number;
            /**
             * @description Accessible URL for viewing or downloading the evidence file.
             * @example /uploads/refunds/ref_543c86069f0f/box_label.jpg
             */
            url: string;
            /**
             * Format: date-time
             * @description ISO-8601 creation timestamp.
             * @example 2026-09-23T14:16:00Z
             */
            createdAt: string;
        };
        ClarificationTurn: {
            /**
             * @description Clarification cycle number (1-indexed).
             * @example 1
             */
            cycle: number;
            /**
             * @description Clarification prompt sent to the customer.
             * @example Please provide a clear photo of the shoe box label.
             */
            prompt?: string | null;
            /**
             * @description Customer response text submitted during this turn.
             * @example Here is the photo of the box label showing size 8.5.
             */
            response?: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when this clarification turn occurred.
             * @example 2026-09-23T14:15:30Z
             */
            timestamp: string;
            /**
             * @description Evidence IDs attached during this clarification turn.
             * @example [
             *       "evi_a1b2c3d4"
             *     ]
             */
            evidenceIds: string[];
        };
        ToolCallAudit: {
            /**
             * @description External verification tool executed (e.g. `query_carrier_tracking` or `query_payment_transaction`).
             * @example query_carrier_tracking
             */
            toolName: string;
            /**
             * @description Arguments supplied to the tool invocation.
             * @example {
             *       "trackingNumber": "TRK-987654"
             *     }
             */
            inputArgs: {
                [key: string]: unknown;
            };
            /**
             * @description Raw response payload received from the external vendor service.
             * @example {
             *       "status": "delivered",
             *       "deliveryTimestamp": "2026-09-20T10:30:00Z"
             *     }
             */
            rawOutput?: {
                [key: string]: unknown;
            };
            /**
             * Format: float
             * @description Execution duration in seconds.
             * @example 0.42
             */
            durationSeconds?: number;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when tool execution completed.
             * @example 2026-09-23T14:10:02Z
             */
            timestamp: string;
        };
        /** @description Evaluated policy rule details matched against the purchase order. */
        MatchedPolicyRule: {
            /**
             * @description Refund category matched by classifier.
             * @example damaged
             */
            category?: string;
            /**
             * @description Name or identifier of the applied policy rule.
             * @example standard_30_day_damaged
             */
            policyName?: string;
            /**
             * @description Prescribed policy action (auto_approve, deny, manual_review).
             * @example auto_approve
             */
            action?: string;
            /**
             * @description Whether customer must return item prior to refund disbursement.
             * @example false
             */
            returnRequired?: boolean;
        };
        RefundDetail: {
            /**
             * @description Unique refund request identifier.
             * @example ref_543c86069f0f
             */
            refundId: string;
            /**
             * @description Associated purchase order identifier.
             * @example ORD-1007
             */
            orderId: string;
            /**
             * @description Original customer refund explanation.
             * @example The chair armrest arrived completely broken and cracked during delivery.
             */
            customerRequestText: string;
            status: components["schemas"]["RefundStatus"];
            /**
             * @description Automated or human-adjudicated refund decision.
             * @example auto_approve
             */
            decision?: components["schemas"]["RefundDecision"] | null;
            /**
             * @description Detailed explanation justifying the decision.
             * @example Refund automatically approved. Category 'damaged' satisfied all policy rules.
             */
            reasoning?: string | null;
            matchedPolicyRule?: components["schemas"]["MatchedPolicyRule"] | null;
            /**
             * Format: float
             * @description Model confidence score (0.0 to 1.0), or null if resolved without LLM.
             * @example 0.95
             */
            confidenceScore?: number | null;
            /**
             * @description Classified refund category.
             * @example damaged
             */
            category?: components["schemas"]["RefundCategory"] | null;
            /**
             * Format: date-time
             * @description ISO-8601 creation timestamp.
             * @example 2026-09-23T14:10:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of last modification.
             * @example 2026-09-23T14:10:05Z
             */
            updatedAt: string;
            /**
             * @description Decision applied by human reviewer override, if applicable.
             * @example null
             */
            overrideDecision?: components["schemas"]["OverrideDecisionType"] | null;
            /**
             * @description Justification provided during human operator override, if applicable.
             * @example null
             */
            overrideReason?: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when manual override occurred, if applicable.
             * @example null
             */
            overriddenAt?: string | null;
            /**
             * @description Question asked to customer for request clarification.
             * @example Could you please provide photos of the damaged shipping box?
             */
            clarificationPrompt?: string | null;
            /**
             * @description Customer-provided clarification response.
             * @example The box was torn open at the bottom corner upon delivery.
             */
            clarificationResponse?: string | null;
            /**
             * @description Number of clarification cycles attempted.
             * @example 0
             */
            clarificationCount?: number;
            /**
             * @description Structured turn-by-turn audit history of clarification and proof request cycles.
             * @example []
             */
            clarificationHistory?: components["schemas"]["ClarificationTurn"][];
            /**
             * @description Customer-uploaded proof attachments (images).
             * @example []
             */
            evidence?: components["schemas"]["EvidenceItem"][];
            /**
             * @description Chronological audit log of external tool invocations, inputs, and results.
             * @example []
             */
            toolCalls?: components["schemas"]["ToolCallAudit"][];
            /**
             * @description Customer confirmation and product return instructions email text generated for approved refunds.
             * @example Dear Customer,
             *
             *     Your refund request has been approved...
             */
            approvalEmailText?: string | null;
            /**
             * @description Customer notification email text explaining policy denial reasoning.
             * @example null
             */
            denialEmailText?: string | null;
            /**
             * @description Customer notification email text requesting evidence or clarification.
             * @example null
             */
            clarificationEmailText?: string | null;
        };
        /** @description RFC 7807 / RFC 9457 problem details object describing an error condition. */
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             * @example urn:problem:not-found
             */
            type: string;
            /**
             * @description Short human-readable summary of problem type.
             * @example Resource Not Found
             */
            title: string;
            /**
             * @description HTTP status code generated by origin server.
             * @example 404
             */
            status: number;
            /**
             * @description Human-readable explanation specific to this occurrence.
             * @example Refund request 'ref_12345' not found.
             */
            detail: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying the specific occurrence of the problem.
             * @example /v1/refunds/ref_12345
             */
            instance?: string;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            /** @description Specific payload or parameter validation failures. */
            invalidParams?: components["schemas"]["InvalidParam"][];
        };
        InvalidParam: {
            /**
             * @description Path or property name that failed validation.
             * @example orderId
             */
            name: string;
            /**
             * @description Description of the validation failure constraint.
             * @example Field cannot be blank or empty.
             */
            reason: string;
        };
    };
    responses: {
        /** @description Bad Request - Malformed request parameters or invalid payload syntax. */
        ProblemBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:problem:bad-request",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "detail": "The request query parameters could not be parsed.",
                 *       "instance": "/v1/refunds"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Not Found - The specified resource does not exist. */
        ProblemNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:problem:not-found",
                 *       "title": "Resource Not Found",
                 *       "status": 404,
                 *       "detail": "Refund request 'ref_nonexistent123' not found.",
                 *       "instance": "/v1/refunds/ref_nonexistent123"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Payload Too Large - Uploaded evidence exceeds maximum file size limit (5MB). */
        ProblemPayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:problem:payload-too-large",
                 *       "title": "Payload Too Large",
                 *       "status": 413,
                 *       "detail": "File size exceeds maximum allowed limit of 5.0 MB.",
                 *       "instance": "/v1/refunds/ref_543c86069f0f/evidence"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unprocessable Content - Request payload failed schema validation rules. */
        ProblemUnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:problem:validation-error",
                 *       "title": "Validation Error",
                 *       "status": 422,
                 *       "detail": "One or more fields in the request body failed validation.",
                 *       "instance": "/v1/refunds",
                 *       "invalidParams": [
                 *         {
                 *           "name": "orderId",
                 *           "reason": "Field cannot be blank or empty."
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description Internal Server Error - An unexpected error occurred while processing the request. */
        ProblemInternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:problem:internal-server-error",
                 *       "title": "Internal Server Error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred while accessing persistence storage.",
                 *       "instance": "/v1/refunds"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /**
         * @description Unique identifier of the refund request (e.g. `ref_543c86069f0f`).
         * @example ref_543c86069f0f
         */
        RefundIdPathParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service information successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "service": "refund-request-processor"
                     *     }
                     */
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
    getHealthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy and responsive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            500: components["responses"]["ProblemInternalServerError"];
            /** @description Service Unavailable - System dependencies are degraded or unhealthy. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "urn:problem:service-unavailable",
                     *       "title": "Service Unavailable",
                     *       "status": 503,
                     *       "detail": "Service is temporarily unable to handle incoming requests.",
                     *       "instance": "/v1/health"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listRefundRequests: {
        parameters: {
            query?: {
                /**
                 * @description Filter refund requests by current workflow processing status.
                 * @example escalated
                 */
                status?: components["schemas"]["RefundStatus"];
                /**
                 * @description Maximum number of refund records to return.
                 * @example 20
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved list of refund requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "refundId": "ref_543c86069f0f",
                     *         "orderId": "ORD-1007",
                     *         "customerRequestText": "The chair armrest arrived completely broken and cracked during delivery.",
                     *         "status": "completed",
                     *         "decision": "auto_approve",
                     *         "reasoning": "Refund automatically approved. Category 'damaged' satisfied all policy rules.",
                     *         "matchedPolicyRule": {
                     *           "category": "damaged",
                     *           "policyName": "standard_30_day_damaged",
                     *           "action": "auto_approve",
                     *           "returnRequired": false
                     *         },
                     *         "confidenceScore": 0.95,
                     *         "category": "damaged",
                     *         "clarificationPrompt": null,
                     *         "clarificationResponse": null,
                     *         "clarificationCount": 0,
                     *         "clarificationHistory": [],
                     *         "evidence": [],
                     *         "toolCalls": [],
                     *         "approvalEmailText": "Dear Customer,\n\nYour refund request has been approved. Your RMA number is RMA-1007-AB12CD.\n\nSincerely,\nCustomer Support Team",
                     *         "denialEmailText": null,
                     *         "clarificationEmailText": null,
                     *         "createdAt": "2026-09-23T14:10:00Z",
                     *         "updatedAt": "2026-09-23T14:10:05Z",
                     *         "overrideDecision": null,
                     *         "overrideReason": null,
                     *         "overriddenAt": null
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["RefundDetail"][];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            422: components["responses"]["ProblemUnprocessableEntity"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
    submitRefundRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Customer order identifier, explanation, and optional evidence image. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "orderId": "ORD-1001",
                 *       "customerRequestText": "The ceramic vase arrived shattered inside the package with no protective bubble wrap."
                 *     }
                 */
                "application/json": components["schemas"]["RefundCreateRequest"];
                "multipart/form-data": {
                    /**
                     * @description Identifier of the order to evaluate.
                     * @example ORD-1001
                     */
                    orderId: string;
                    /**
                     * @description Customer refund explanation.
                     * @example The ceramic vase arrived shattered inside the package.
                     */
                    customerRequestText: string;
                    /**
                     * Format: binary
                     * @description Optional supporting proof photo (JPEG, PNG, WebP up to 5MB).
                     */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Refund request accepted for background processing. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "refundId": "ref_7f9b1c2e3a4d",
                     *       "orderId": "ORD-1001",
                     *       "status": "pending",
                     *       "createdAt": "2026-09-23T14:15:30Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RefundCreateResponse"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            413: components["responses"]["ProblemPayloadTooLarge"];
            422: components["responses"]["ProblemUnprocessableEntity"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
    getRefundRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the refund request (e.g. `ref_543c86069f0f`).
                 * @example ref_543c86069f0f
                 */
                refundId: components["parameters"]["RefundIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detailed refund request record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "refundId": "ref_543c86069f0f",
                     *       "orderId": "ORD-1007",
                     *       "customerRequestText": "Received wrong shoe size (ordered 10, received 8.5).",
                     *       "status": "escalated",
                     *       "decision": "escalate",
                     *       "reasoning": "Escalated to human review due to ambiguous item condition.",
                     *       "matchedPolicyRule": {
                     *         "category": "wrong_item",
                     *         "policyName": "wrong_item_exchange_policy",
                     *         "action": "manual_review",
                     *         "returnRequired": true
                     *       },
                     *       "confidenceScore": 0.88,
                     *       "category": "wrong_item",
                     *       "clarificationPrompt": null,
                     *       "clarificationResponse": null,
                     *       "clarificationCount": 0,
                     *       "clarificationHistory": [],
                     *       "evidence": [],
                     *       "toolCalls": [],
                     *       "approvalEmailText": null,
                     *       "denialEmailText": null,
                     *       "clarificationEmailText": null,
                     *       "createdAt": "2026-09-23T14:10:00Z",
                     *       "updatedAt": "2026-09-23T14:10:04Z",
                     *       "overrideDecision": null,
                     *       "overrideReason": null,
                     *       "overriddenAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["RefundDetail"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            404: components["responses"]["ProblemNotFound"];
            422: components["responses"]["ProblemUnprocessableEntity"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
    overrideRefundDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the refund request (e.g. `ref_543c86069f0f`).
                 * @example ref_543c86069f0f
                 */
                refundId: components["parameters"]["RefundIdPathParam"];
            };
            cookie?: never;
        };
        /** @description Operator manual decision and justification. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "overrideDecision": "approve",
                 *       "overrideReason": "Verified return tracking code delivered to warehouse. Discretionary customer satisfaction approval."
                 *     }
                 */
                "application/json": components["schemas"]["RefundOverrideRequest"];
            };
        };
        responses: {
            /** @description Override successfully recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "refundId": "ref_543c86069f0f",
                     *       "orderId": "ORD-1007",
                     *       "customerRequestText": "Received wrong shoe size (ordered 10, received 8.5).",
                     *       "status": "completed",
                     *       "decision": "approve",
                     *       "reasoning": "Escalated to human review due to ambiguous item condition.",
                     *       "matchedPolicyRule": {
                     *         "category": "wrong_item",
                     *         "policyName": "wrong_item_exchange_policy",
                     *         "action": "manual_review",
                     *         "returnRequired": true
                     *       },
                     *       "confidenceScore": 0.88,
                     *       "category": "wrong_item",
                     *       "clarificationPrompt": null,
                     *       "clarificationResponse": null,
                     *       "clarificationCount": 0,
                     *       "clarificationHistory": [],
                     *       "evidence": [],
                     *       "toolCalls": [],
                     *       "approvalEmailText": null,
                     *       "denialEmailText": null,
                     *       "clarificationEmailText": null,
                     *       "createdAt": "2026-09-23T14:10:00Z",
                     *       "updatedAt": "2026-09-23T14:25:12Z",
                     *       "overrideDecision": "approve",
                     *       "overrideReason": "Verified return tracking code delivered to warehouse. Discretionary customer satisfaction approval.",
                     *       "overriddenAt": "2026-09-23T14:25:12Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RefundDetail"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            404: components["responses"]["ProblemNotFound"];
            422: components["responses"]["ProblemUnprocessableEntity"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
    submitRefundClarification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the refund request (e.g. `ref_543c86069f0f`).
                 * @example ref_543c86069f0f
                 */
                refundId: components["parameters"]["RefundIdPathParam"];
            };
            cookie?: never;
        };
        /** @description Customer clarification response text and optional evidence image. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "responseText": "The package was left at the front porch in heavy rain, soaked through."
                 *     }
                 */
                "application/json": components["schemas"]["RefundClarificationRequest"];
                "multipart/form-data": {
                    /**
                     * @description Customer clarification explanation.
                     * @example Item arrived damaged with ripped outer box.
                     */
                    responseText: string;
                    /**
                     * Format: binary
                     * @description Optional supporting proof photo (JPEG, PNG, WebP up to 5MB).
                     */
                    evidenceFile?: string;
                };
            };
        };
        responses: {
            /** @description Clarification accepted and workflow resumed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "refundId": "ref_543c86069f0f",
                     *       "orderId": "ORD-1007",
                     *       "customerRequestText": "Received wrong shoe size (ordered 10, received 8.5).",
                     *       "status": "pending",
                     *       "decision": null,
                     *       "reasoning": null,
                     *       "matchedPolicyRule": null,
                     *       "confidenceScore": null,
                     *       "category": "wrong_item",
                     *       "clarificationPrompt": "Could you please specify if the packaging was unopened?",
                     *       "clarificationResponse": "The package was left at the front porch in heavy rain, soaked through.",
                     *       "clarificationCount": 1,
                     *       "clarificationHistory": [
                     *         {
                     *           "cycle": 1,
                     *           "prompt": "Could you please specify if the packaging was unopened?",
                     *           "response": "The package was left at the front porch in heavy rain, soaked through.",
                     *           "timestamp": "2026-09-23T14:15:30Z",
                     *           "evidenceIds": []
                     *         }
                     *       ],
                     *       "evidence": [],
                     *       "toolCalls": [],
                     *       "approvalEmailText": null,
                     *       "denialEmailText": null,
                     *       "clarificationEmailText": null,
                     *       "createdAt": "2026-09-23T14:10:00Z",
                     *       "updatedAt": "2026-09-23T14:15:30Z",
                     *       "overrideDecision": null,
                     *       "overrideReason": null,
                     *       "overriddenAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["RefundDetail"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            404: components["responses"]["ProblemNotFound"];
            413: components["responses"]["ProblemPayloadTooLarge"];
            422: components["responses"]["ProblemUnprocessableEntity"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
    uploadRefundEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the refund request (e.g. `ref_543c86069f0f`).
                 * @example ref_543c86069f0f
                 */
                refundId: components["parameters"]["RefundIdPathParam"];
            };
            cookie?: never;
        };
        /** @description Multipart image file to attach as proof. */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Evidence photo file (JPEG, PNG, WebP up to 5MB).
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Photo evidence successfully uploaded and attached to refund record. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "refundId": "ref_543c86069f0f",
                     *       "orderId": "ORD-1007",
                     *       "customerRequestText": "Received wrong shoe size (ordered 10, received 8.5).",
                     *       "status": "pending",
                     *       "decision": null,
                     *       "reasoning": null,
                     *       "matchedPolicyRule": null,
                     *       "confidenceScore": null,
                     *       "category": "wrong_item",
                     *       "clarificationPrompt": "Please provide a clear photo of the shoe box label.",
                     *       "clarificationResponse": null,
                     *       "clarificationCount": 1,
                     *       "clarificationHistory": [
                     *         {
                     *           "cycle": 1,
                     *           "prompt": "Please provide a clear photo of the shoe box label.",
                     *           "response": null,
                     *           "timestamp": "2026-09-23T14:15:30Z",
                     *           "evidenceIds": [
                     *             "evi_a1b2c3d4"
                     *           ]
                     *         }
                     *       ],
                     *       "evidence": [
                     *         {
                     *           "evidenceId": "evi_a1b2c3d4",
                     *           "storageKey": "refunds/ref_543c86069f0f/box_label.jpg",
                     *           "filename": "box_label.jpg",
                     *           "contentType": "image/jpeg",
                     *           "sizeBytes": 154230,
                     *           "url": "/uploads/refunds/ref_543c86069f0f/box_label.jpg",
                     *           "createdAt": "2026-09-23T14:16:00Z"
                     *         }
                     *       ],
                     *       "toolCalls": [],
                     *       "approvalEmailText": null,
                     *       "denialEmailText": null,
                     *       "clarificationEmailText": null,
                     *       "createdAt": "2026-09-23T14:10:00Z",
                     *       "updatedAt": "2026-09-23T14:16:00Z",
                     *       "overrideDecision": null,
                     *       "overrideReason": null,
                     *       "overriddenAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["RefundDetail"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            404: components["responses"]["ProblemNotFound"];
            413: components["responses"]["ProblemPayloadTooLarge"];
            422: components["responses"]["ProblemUnprocessableEntity"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
    requestReviewerProof: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of the refund request (e.g. `ref_543c86069f0f`).
                 * @example ref_543c86069f0f
                 */
                refundId: components["parameters"]["RefundIdPathParam"];
            };
            cookie?: never;
        };
        /** @description Reviewer proof prompt and optional customer greeting name. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "proofPrompt": "Please provide a clear photo of the serial number sticker on the base of the device.",
                 *       "customerName": "Alex Morgan"
                 *     }
                 */
                "application/json": components["schemas"]["ReviewerProofRequest"];
            };
        };
        responses: {
            /** @description Reviewer proof request recorded and transitioned to awaiting_clarification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "refundId": "ref_543c86069f0f",
                     *       "orderId": "ORD-1007",
                     *       "customerRequestText": "Device stopped charging after two weeks.",
                     *       "status": "awaiting_clarification",
                     *       "decision": null,
                     *       "reasoning": null,
                     *       "matchedPolicyRule": null,
                     *       "confidenceScore": null,
                     *       "category": "damaged",
                     *       "clarificationPrompt": "Please provide a clear photo of the serial number sticker on the base of the device.",
                     *       "clarificationResponse": null,
                     *       "clarificationCount": 1,
                     *       "clarificationHistory": [
                     *         {
                     *           "cycle": 1,
                     *           "prompt": "Please provide a clear photo of the serial number sticker on the base of the device.",
                     *           "response": null,
                     *           "timestamp": "2026-09-23T14:30:00Z",
                     *           "evidenceIds": []
                     *         }
                     *       ],
                     *       "evidence": [],
                     *       "toolCalls": [],
                     *       "approvalEmailText": null,
                     *       "denialEmailText": null,
                     *       "clarificationEmailText": "Dear Alex Morgan,\n\nOur quality review team requires additional proof regarding order ORD-1007.\nPlease provide a clear photo of the serial number sticker on the base of the device.\n\nAccepted formats: JPEG, PNG, WebP up to 5MB.",
                     *       "createdAt": "2026-09-23T14:10:00Z",
                     *       "updatedAt": "2026-09-23T14:30:00Z",
                     *       "overrideDecision": null,
                     *       "overrideReason": null,
                     *       "overriddenAt": null
                     *     }
                     */
                    "application/json": components["schemas"]["RefundDetail"];
                };
            };
            400: components["responses"]["ProblemBadRequest"];
            404: components["responses"]["ProblemNotFound"];
            422: components["responses"]["ProblemUnprocessableEntity"];
            500: components["responses"]["ProblemInternalServerError"];
        };
    };
}
